"""Background watcher for job completion, notifications, and auto-preview workflows."""

from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from typing import Optional

from app.auth import _decrypt_password
from app.core.bot_core import notified_jobs
from app.core.config import settings
from app.storage.database import get_db_connection
from app.services.preview.runtime import (
    _notify_preview_job_completion,
    _notify_preview_job_failure,
    preview_message_registry,
)

logger = logging.getLogger(__name__)


@dataclass(slots=True)
class _WatcherUser:
    telegram_user_id: int
    login: str
    password: str


def _extract_preview_owner_id(props: dict, job_id: str) -> Optional[int]:
    extra_dict = props.get("ExDic") or {}
    if not isinstance(extra_dict, dict):
        extra_dict = {}

    preview_owner_str = extra_dict.get("PreviewTelegram")
    for key in (
        "ExtraInfoKeyValue0",
        "ExtraInfoKeyValue1",
        "ExtraInfoKeyValue2",
        "ExtraInfoKeyValue3",
        "ExtraInfoKeyValue4",
    ):
        value = props.get(key)
        if not value or "=" not in value:
            continue
        prefix, payload = value.split("=", 1)
        if prefix == "PreviewTelegram":
            preview_owner_str = payload

    if not preview_owner_str:
        return None

    try:
        return int(str(preview_owner_str).strip())
    except (TypeError, ValueError):
        logger.warning(
            "Invalid PreviewTelegram value '%s' for job %s",
            preview_owner_str,
            job_id,
        )
        return None


def _is_preview_job(props: dict) -> bool:
    comment = str(props.get("Cmmt") or "")
    name = str(props.get("Name") or "").split("/")[-1]
    extra_dict = props.get("ExDic") or {}
    if not isinstance(extra_dict, dict):
        extra_dict = {}
    return (
        "Preview job generated by TasksBot" in comment
        or name.endswith(" - Preview")
        or extra_dict.get("PreviewJob") == "1"
    )


def _is_recently_completed(job: dict, props: dict) -> bool:
    date_comp_str = job.get("DateComp") or props.get("DateComp")
    if not date_comp_str or date_comp_str == "0001-01-01T00:00:00Z":
        return False

    try:
        date_comp = datetime.fromisoformat(date_comp_str.replace("Z", "+00:00"))
    except Exception:
        return False

    now = datetime.now(timezone.utc)
    return (now - date_comp) <= timedelta(minutes=10)


async def _load_watcher_users() -> list[_WatcherUser]:
    conn = get_db_connection()
    if conn is None:
        return []

    user_rows = []
    try:
        async with conn.execute(
            """
            SELECT telegram_user_id,
                   deadline_login,
                   deadline_password
            FROM user_sessions
            """
        ) as cursor:
            user_rows = await cursor.fetchall()
    except Exception as exc:
        logger.error("Error fetching users for monitoring: %s", exc)
        return []

    users: list[_WatcherUser] = []
    for row in user_rows:
        user_id, login, encrypted_password = row

        try:
            decrypted_password = _decrypt_password(encrypted_password)
        except Exception:
            decrypted_password = encrypted_password

        users.append(
            _WatcherUser(
                telegram_user_id=int(user_id),
                login=str(login),
                password=str(decrypted_password),
            )
        )

    return users


def _collect_active_preview_targets(
    users: list[_WatcherUser],
) -> list[tuple[str, _WatcherUser]]:
    if not users or not preview_message_registry:
        return []

    users_by_id = {user.telegram_user_id: user for user in users}
    targets: list[tuple[str, _WatcherUser]] = []
    for preview_job_id, (chat_id, _message_id) in preview_message_registry.items():
        try:
            chat_id_int = int(chat_id)
        except (TypeError, ValueError):
            continue
        user = users_by_id.get(chat_id_int)
        if user is None:
            continue
        targets.append((preview_job_id, user))
    return targets


async def _process_active_preview_job(
    preview_job_id: str,
    user: _WatcherUser,
) -> None:
    from app.services.deadline import get_job_info_direct

    try:
        job = await get_job_info_direct(user.login, user.password, preview_job_id)
    except Exception as exc:
        logger.error(
            "Watcher: failed loading preview job %s for user %s: %s",
            preview_job_id,
            user.telegram_user_id,
            exc,
        )
        return

    if not job:
        return

    props = job.get("Props", {})
    if not _is_preview_job(props):
        return

    preview_owner_id = _extract_preview_owner_id(props, preview_job_id)
    target_user = preview_owner_id or user.telegram_user_id
    if target_user != user.telegram_user_id:
        return

    stat = job.get("Stat", 0)
    name = str(props.get("Name") or "").split("/")[-1]
    notified_key = (preview_job_id, target_user)

    if stat == 4:
        if notified_key in notified_jobs:
            return
        notified_user_id = await _notify_preview_job_failure(
            user.telegram_user_id,
            job,
            name,
            user.login,
            user.password,
        )
        resolved_user_id = notified_user_id or target_user
        notified_jobs.add((preview_job_id, resolved_user_id))
        return

    if stat != 3 or not _is_recently_completed(job, props):
        return

    if notified_key in notified_jobs:
        return
    notified_user_id = await _notify_preview_job_completion(
        user.telegram_user_id,
        job,
        name,
        user.login,
        user.password,
    )
    resolved_user_id = notified_user_id or target_user
    notified_jobs.add((preview_job_id, resolved_user_id))


async def _process_active_previews_parallel(
    targets: list[tuple[str, _WatcherUser]],
) -> None:
    if not targets:
        return

    max_parallel = min(8, max(1, len(targets)))
    semaphore = asyncio.Semaphore(max_parallel)

    async def _run(job_id: str, user: _WatcherUser) -> None:
        async with semaphore:
            await _process_active_preview_job(job_id, user)

    tasks = [asyncio.create_task(_run(job_id, user)) for job_id, user in targets]
    results = await asyncio.gather(*tasks, return_exceptions=True)
    for (job_id, user), result in zip(targets, results):
        if isinstance(result, Exception):
            logger.error(
                "Watcher: active preview processing failed for user %s job %s: %s",
                user.telegram_user_id,
                job_id,
                result,
            )


async def job_progress_watcher(bot) -> None:
    """Monitor active preview jobs and send completion/failure notifications."""
    try:
        while True:
            has_active_previews = len(preview_message_registry) > 0
            sleep_interval = (
                settings.job_watcher_interval_preview
                if has_active_previews
                else settings.job_watcher_interval_normal
            )

            if has_active_previews:
                logger.debug(
                    "Active preview jobs: %s, using fast polling (%ss)",
                    len(preview_message_registry),
                    sleep_interval,
                )

            await asyncio.sleep(sleep_interval)
            if not has_active_previews:
                continue

            users = await _load_watcher_users()
            targets = _collect_active_preview_targets(users)
            logger.info(
                "Job progress watcher: Monitoring %d active preview jobs for %d users",
                len(targets),
                len(users),
            )
            await _process_active_previews_parallel(targets)
    except asyncio.CancelledError:
        logger.info("Job progress watcher cancelled")
