"""Background watcher for preview completion and auto-preview workflows."""

from __future__ import annotations

import asyncio
import html
import logging
import re
import time
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from typing import Callable, Literal, Optional

from app.auth import _decrypt_password
from app.core.bot_core import auto_preview_jobs, bot, notified_jobs
from app.core.config import settings
from app.core.ttl_cache import TTLCache
from app.storage.database import get_db_connection
from app.services.preview.runtime import (
    _notify_preview_job_completion,
    _notify_preview_job_failure,
    _run_auto_preview_for_job,
    preview_message_registry,
)
from app.storage.user_settings import VALID_PREVIEW_RENDER_METHODS, _normalize_scope

logger = logging.getLogger(__name__)

_UNABLE_TO_OPEN_FILE_RE = re.compile(
    r"unable to open file:\s*([a-z]:[^\r\n]+)",
    re.IGNORECASE,
)
_INPUT_FILE_RE = re.compile(
    r"input file:\s*([a-z]:[^\r\n]+)",
    re.IGNORECASE,
)

_AUTO_PREVIEW_SCAN_INTERVAL_SECONDS = 30
_AUTO_PREVIEW_HISTORY_RETENTION_SECONDS = 14 * 24 * 60 * 60
_AUTO_PREVIEW_HISTORY_CLEANUP_INTERVAL_SECONDS = 60 * 60
_ERROR_REPORT_SCAN_INTERVAL_SECONDS = 10
_ERROR_REPORT_MAX_AGE_SECONDS = 24 * 60 * 60
_ERROR_ALERT_CACHE_TTL_SECONDS = 14 * 24 * 60 * 60
_last_auto_preview_history_cleanup_monotonic = 0.0
_error_alert_cache = TTLCache(
    ttl_seconds=_ERROR_ALERT_CACHE_TTL_SECONDS,
    max_size=100000,
)
_ERROR_ALERT_RECIPIENT_MODE_JOB_USER = "job_user"
_ERROR_ALERT_RECIPIENT_MODE_ERROR_WORKER = "error_worker"
_ERROR_ALERT_RECIPIENT_MODE_BOTH = "both"
_ERROR_ALERT_SEVERITY_CRITICAL = "critical"
_ERROR_ALERT_SEVERITY_WARNING = "warning"
_ERROR_ALERT_SEVERITY_INFO = "info"
_ErrorAlertRecipientMode = Literal[
    "job_user",
    "error_worker",
    "both",
]
_ErrorAlertSeverity = Literal[
    "critical",
    "warning",
    "info",
]


@dataclass(slots=True)
class _WatcherUser:
    telegram_user_id: int
    login: str
    password: str
    notifications_enabled: bool
    notification_scope: str
    auto_scope: str
    preview_method: Optional[str]
    preview_worker: Optional[str]
    auto_preview_enabled: bool


@dataclass(frozen=True, slots=True)
class _ErrorAlertRule:
    key: str
    label: str
    matcher: Callable[[dict], bool]
    recipient_mode: _ErrorAlertRecipientMode
    severity: _ErrorAlertSeverity


def _normalize_identity(value: object) -> str:
    raw = str(value or "").strip().lower()
    if not raw:
        return ""
    return raw.split("\\")[-1].split("/")[-1]


def _identity_variants(value: object) -> set[str]:
    raw = str(value or "").strip().lower()
    if not raw:
        return set()
    short = raw.split("\\")[-1].split("/")[-1]
    return {raw, short}


def _job_matches_scope(scope_value: str, login_value: str, props: dict, job_entry: dict) -> bool:
    if scope_value != "own":
        return True
    job_owner = props.get("User") or job_entry.get("UserName") or ""
    if not job_owner:
        return False
    normalized_login = str(login_value).split("\\")[-1].split("/")[-1].lower()
    normalized_owner = str(job_owner).split("\\")[-1].split("/")[-1].lower()
    return normalized_owner == normalized_login


def _extract_preview_owner_id(props: dict, job_id: str) -> Optional[int]:
    extra_dict = props.get("ExDic") or {}
    if not isinstance(extra_dict, dict):
        extra_dict = {}

    preview_owner_str = extra_dict.get("PreviewTelegram")
    for key in (
        "ExtraInfoKeyValue0",
        "ExtraInfoKeyValue1",
        "ExtraInfoKeyValue2",
        "ExtraInfoKeyValue3",
        "ExtraInfoKeyValue4",
    ):
        value = props.get(key)
        if not value or "=" not in value:
            continue
        prefix, payload = value.split("=", 1)
        if prefix == "PreviewTelegram":
            preview_owner_str = payload

    if not preview_owner_str:
        return None

    try:
        return int(str(preview_owner_str).strip())
    except (TypeError, ValueError):
        logger.warning(
            "Invalid PreviewTelegram value '%s' for job %s",
            preview_owner_str,
            job_id,
        )
        return None


def _is_preview_job(props: dict) -> bool:
    comment = str(props.get("Cmmt") or "")
    name = str(props.get("Name") or "").split("/")[-1]
    extra_dict = props.get("ExDic") or {}
    if not isinstance(extra_dict, dict):
        extra_dict = {}
    return (
        "Preview job generated by TasksBot" in comment
        or name.endswith(" - Preview")
        or extra_dict.get("PreviewJob") == "1"
    )


def _is_recently_completed(job: dict, props: dict) -> bool:
    date_comp_str = job.get("DateComp") or props.get("DateComp")
    if not date_comp_str or date_comp_str == "0001-01-01T00:00:00Z":
        return False

    try:
        date_comp = datetime.fromisoformat(date_comp_str.replace("Z", "+00:00"))
    except Exception:
        return False

    now = datetime.now(timezone.utc)
    return (now - date_comp) <= timedelta(minutes=10)


def _parse_datetime_utc(raw_value: object) -> Optional[datetime]:
    if not raw_value:
        return None
    raw = str(raw_value).strip()
    if not raw or raw == "0001-01-01T00:00:00Z":
        return None
    try:
        parsed = datetime.fromisoformat(raw.replace("Z", "+00:00"))
    except Exception:
        return None
    if parsed.tzinfo is None:
        return parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def _is_job_candidate_for_error_scan(job: dict) -> bool:
    stat = int(job.get("Stat", 0) or 0)
    # Scan only jobs that are rendering or waiting to render.
    return stat in {1, 6}  # Active, Pending


def _matches_redshift_activation_error(report: dict) -> bool:
    title = str(report.get("Title") or "")
    log_err = str(report.get("LogErr") or "")
    combined = f"{title}\n{log_err}".lower()
    return "redshift activation" in combined


def _report_search_text(report: dict) -> str:
    chunks: list[str] = []

    def walk(node: object) -> None:
        if len(chunks) >= 64:
            return
        if isinstance(node, dict):
            for value in node.values():
                walk(value)
        elif isinstance(node, list):
            for value in node:
                walk(value)
        elif isinstance(node, str):
            text = node.strip()
            if text:
                chunks.append(text)

    walk(report)
    return "\n".join(chunks)


def _clean_report_path(raw_path: str) -> str:
    return raw_path.strip().strip('"').strip("'").rstrip(".")


def _extract_report_path(report: dict) -> Optional[str]:
    search_text = _report_search_text(report)
    for pattern in (_UNABLE_TO_OPEN_FILE_RE, _INPUT_FILE_RE):
        match = pattern.search(search_text)
        if match:
            candidate = _clean_report_path(match.group(1))
            if candidate:
                return candidate
    return None


def _matches_local_c_drive_open_error(report: dict) -> bool:
    search_text = _report_search_text(report)
    if not search_text:
        return False

    normalized = search_text.lower()
    if "unable to open file:" not in normalized:
        return False

    path = _extract_report_path(report)
    if not path or not path.lower().startswith("c:"):
        return False

    return True


# Add new report alert types here: key + display label + predicate.
_ERROR_ALERT_RULES: tuple[_ErrorAlertRule, ...] = (
    _ErrorAlertRule(
        key="redshift_activation",
        label="Redshift activation error",
        matcher=_matches_redshift_activation_error,
        recipient_mode=_ERROR_ALERT_RECIPIENT_MODE_BOTH,
        severity=_ERROR_ALERT_SEVERITY_CRITICAL,
    ),
    _ErrorAlertRule(
        key="local_c_drive_open_error",
        label="Local C: path is not accessible on worker",
        matcher=_matches_local_c_drive_open_error,
        recipient_mode=_ERROR_ALERT_RECIPIENT_MODE_JOB_USER,
        severity=_ERROR_ALERT_SEVERITY_WARNING,
    ),
)


def _match_error_alert_rule(report: dict) -> Optional[_ErrorAlertRule]:
    for rule in _ERROR_ALERT_RULES:
        try:
            if rule.matcher(report):
                return rule
        except Exception:
            continue
    return None


def _is_recent_error_report(report: dict) -> bool:
    reported_at = _parse_datetime_utc(report.get("Date"))
    if reported_at is None:
        return True
    return (
        datetime.now(timezone.utc) - reported_at
    ) <= timedelta(seconds=_ERROR_REPORT_MAX_AGE_SECONDS)


def _report_dedupe_id(job_id: str, report: dict, rule_key: str) -> str:
    if rule_key == "local_c_drive_open_error":
        return f"{rule_key}:{str(job_id or '').strip()}"

    report_id = str(report.get("_id") or "").strip()
    if report_id:
        return f"{rule_key}:{report_id}"
    fallback = "|".join(
        [
            str(rule_key or "").strip(),
            str(job_id or "").strip(),
            str(report.get("Task") or "").strip(),
            str(report.get("Slave") or "").strip(),
            str(report.get("Date") or "").strip(),
            str(report.get("Title") or "").strip(),
        ]
    )
    return fallback


def _build_error_alert_text(report: dict, rule: _ErrorAlertRule) -> str:
    worker_name = html.escape(str(report.get("Slave") or "Unknown"))
    job_name = html.escape(str(report.get("JobName") or report.get("Job") or "Unknown job"))
    title_raw = str(report.get("Title") or report.get("LogErr") or "Unknown error").strip()
    if len(title_raw) > 900:
        title_raw = title_raw[:897].rstrip() + "..."
    error_text = html.escape(title_raw)
    rule_label = html.escape(rule.label)
    severity_icon, severity_label = _format_error_alert_severity(rule.severity)

    header_lines = [
        f"{severity_icon} <b>{severity_label}</b>",
        "",
        f"🏷️ <b>Issue</b>: <code>{rule_label}</code>",
        "",
        f"🎬 <b>Job</b>: <code>{job_name}</code>",
        f"🖥️ <b>Worker</b>: <code>{worker_name}</code>",
    ]

    if rule.key == "local_c_drive_open_error":
        local_path = _extract_report_path(report)
        details = list(header_lines)
        if local_path:
            details.extend(
                [
                    "",
                    "📁 <b>Path</b>:",
                    f"<code>{html.escape(local_path)}</code>",
                ]
            )
        details.extend(
            [
                "",
                "💡 <b>What To Do</b>:",
                "• Submit the scene from a shared or network path.",
                "• Do not submit from a local <code>C:</code> path that exists only on your workstation.",
            ]
        )
        return "\n".join(details)

    return "\n".join(
        header_lines
        + [
            "",
            f"📝 <b>Message</b>: <code>{error_text}</code>",
        ]
    )


def _format_error_alert_severity(severity: _ErrorAlertSeverity) -> tuple[str, str]:
    if severity == _ERROR_ALERT_SEVERITY_CRITICAL:
        return "🔴", "Critical"
    if severity == _ERROR_ALERT_SEVERITY_WARNING:
        return "🟡", "Warning"
    return "🟢", "Info"


def _build_notification_users_by_identity(
    users: list[_WatcherUser],
) -> dict[str, set[int]]:
    identity_map: dict[str, set[int]] = {}
    for user in users:
        for variant in _identity_variants(user.login):
            bucket = identity_map.setdefault(variant, set())
            bucket.add(user.telegram_user_id)
    return identity_map


def _report_debug_summary(report: dict) -> str:
    report_id = str(report.get("_id") or "-").strip()
    slave = str(report.get("Slave") or "-").strip()
    job_user = str(report.get("JobUser") or "-").strip()
    title = str(report.get("Title") or report.get("LogErr") or "").strip().replace("\r", " ").replace("\n", " ")
    if len(title) > 140:
        title = title[:137].rstrip() + "..."
    path = _extract_report_path(report) or "-"
    has_contents = bool(str(report.get("ErrorContents") or "").strip())
    return (
        f"report_id={report_id} slave={slave} job_user={job_user} "
        f"has_contents={int(has_contents)} path={path} title={title or '-'}"
    )


def _resolve_error_alert_recipient_ids(
    report: dict,
    recipient_mode: _ErrorAlertRecipientMode,
    users_by_identity: dict[str, set[int]],
) -> set[int]:
    recipient_ids: set[int] = set()

    if recipient_mode in {
        _ERROR_ALERT_RECIPIENT_MODE_JOB_USER,
        _ERROR_ALERT_RECIPIENT_MODE_BOTH,
    }:
        job_user = _normalize_identity(report.get("JobUser"))
        if job_user:
            recipient_ids.update(users_by_identity.get(job_user, set()))

    if recipient_mode in {
        _ERROR_ALERT_RECIPIENT_MODE_ERROR_WORKER,
        _ERROR_ALERT_RECIPIENT_MODE_BOTH,
    }:
        error_worker = _normalize_identity(report.get("Slave"))
        if error_worker:
            recipient_ids.update(users_by_identity.get(error_worker, set()))

    return recipient_ids


async def _scan_error_reports_candidates(users: list[_WatcherUser]) -> int:
    """Scan Deadline job error reports and notify users by configured alert rules."""
    from app.services.deadline import (
        get_job_error_reports,
        get_job_report_contents,
        get_jobs_by_credentials,
    )

    notification_users = [user for user in users if user.notifications_enabled]
    if not notification_users:
        return 0
    users_by_identity = _build_notification_users_by_identity(notification_users)

    max_parallel = min(4, max(1, len(notification_users)))
    semaphore = asyncio.Semaphore(max_parallel)

    async def _scan_user(user: _WatcherUser) -> int:
        async with semaphore:
            try:
                jobs = await get_jobs_by_credentials(
                    user.login,
                    user.password,
                    use_cache=True,
                )
            except Exception as exc:
                logger.error(
                    "Watcher: failed loading jobs for notifications user %s: %s",
                    user.telegram_user_id,
                    exc,
                )
                return 0

            logger.info(
                "Watcher: notification scan start user_id=%s login=%s scope=%s jobs=%s",
                user.telegram_user_id,
                user.login,
                user.notification_scope,
                len(jobs),
            )

            candidate_job_ids: list[str] = []
            seen_job_ids: set[str] = set()
            for job in jobs:
                if not isinstance(job, dict):
                    continue

                job_id_raw = job.get("_id")
                job_id = str(job_id_raw).strip() if job_id_raw else ""
                if not job_id or job_id in seen_job_ids:
                    continue

                props = job.get("Props") or {}
                if not isinstance(props, dict):
                    props = {}

                if _is_preview_job(props):
                    continue
                if not _job_matches_scope(user.notification_scope, user.login, props, job):
                    continue
                if not _is_job_candidate_for_error_scan(job):
                    continue

                seen_job_ids.add(job_id)
                candidate_job_ids.append(job_id)
                if len(candidate_job_ids) >= 40:
                    break

            logger.info(
                "Watcher: notification scan candidates user_id=%s login=%s candidate_jobs=%s ids=%s",
                user.telegram_user_id,
                user.login,
                len(candidate_job_ids),
                candidate_job_ids[:10],
            )

            sent_count = 0
            for job_id in candidate_job_ids:
                try:
                    reports = await get_job_error_reports(user.login, user.password, job_id)
                except Exception as exc:
                    logger.error(
                        "Watcher: failed loading error reports for user %s job %s: %s",
                        user.telegram_user_id,
                        job_id,
                        exc,
                    )
                    continue

                logger.info(
                    "Watcher: loaded error reports user_id=%s login=%s job_id=%s count=%s",
                    user.telegram_user_id,
                    user.login,
                    job_id,
                    len(reports),
                )

                for report in reports:
                    if not isinstance(report, dict):
                        continue
                    if not _is_recent_error_report(report):
                        logger.info(
                            "Watcher: skipped stale report user_id=%s job_id=%s %s",
                            user.telegram_user_id,
                            job_id,
                            _report_debug_summary(report),
                        )
                        continue
                    report_payload = report
                    matched_rule = _match_error_alert_rule(report_payload)
                    logger.info(
                        "Watcher: short report evaluation user_id=%s job_id=%s matched_rule=%s %s",
                        user.telegram_user_id,
                        job_id,
                        matched_rule.key if matched_rule else "-",
                        _report_debug_summary(report_payload),
                    )
                    if matched_rule is None:
                        report_id = str(report.get("_id") or "").strip()
                        if report_id:
                            try:
                                report_contents = await get_job_report_contents(
                                    user.login,
                                    user.password,
                                    job_id,
                                    report_id,
                                )
                            except Exception as exc:
                                logger.error(
                                    "Watcher: failed loading error contents for user %s job %s report %s: %s",
                                    user.telegram_user_id,
                                    job_id,
                                    report_id,
                                    exc,
                                )
                                report_contents = None

                            if report_contents:
                                logger.info(
                                    "Watcher: loaded error contents user_id=%s job_id=%s report_id=%s chars=%s",
                                    user.telegram_user_id,
                                    job_id,
                                    report_id,
                                    len(report_contents),
                                )
                                report_payload = dict(report)
                                report_payload["ErrorContents"] = report_contents
                                matched_rule = _match_error_alert_rule(report_payload)
                                logger.info(
                                    "Watcher: full report evaluation user_id=%s job_id=%s matched_rule=%s %s",
                                    user.telegram_user_id,
                                    job_id,
                                    matched_rule.key if matched_rule else "-",
                                    _report_debug_summary(report_payload),
                                )
                            else:
                                logger.info(
                                    "Watcher: no error contents user_id=%s job_id=%s report_id=%s",
                                    user.telegram_user_id,
                                    job_id,
                                    report_id,
                                )

                    if matched_rule is None:
                        logger.info(
                            "Watcher: no alert rule matched user_id=%s job_id=%s %s",
                            user.telegram_user_id,
                            job_id,
                            _report_debug_summary(report_payload),
                        )
                        continue

                    dedupe_id = _report_dedupe_id(job_id, report, matched_rule.key)
                    if not dedupe_id:
                        logger.info(
                            "Watcher: empty dedupe id user_id=%s job_id=%s rule=%s",
                            user.telegram_user_id,
                            job_id,
                            matched_rule.key,
                        )
                        continue
                    recipient_ids = _resolve_error_alert_recipient_ids(
                        report_payload,
                        matched_rule.recipient_mode,
                        users_by_identity,
                    )
                    logger.info(
                        "Watcher: recipient resolution user_id=%s job_id=%s rule=%s mode=%s recipients=%s",
                        user.telegram_user_id,
                        job_id,
                        matched_rule.key,
                        matched_rule.recipient_mode,
                        sorted(recipient_ids),
                    )
                    if not recipient_ids:
                        continue

                    alert_text = _build_error_alert_text(report_payload, matched_rule)
                    for recipient_user_id in recipient_ids:
                        dedupe_key = (dedupe_id, recipient_user_id)
                        if dedupe_key in _error_alert_cache:
                            logger.info(
                                "Watcher: skipped duplicate alert user_id=%s job_id=%s recipient=%s dedupe_id=%s",
                                user.telegram_user_id,
                                job_id,
                                recipient_user_id,
                                dedupe_id,
                            )
                            continue

                        try:
                            await bot.send_message(
                                recipient_user_id,
                                alert_text,
                                parse_mode="HTML",
                            )
                        except Exception as exc:
                            logger.error(
                                "Watcher: failed sending report alert to user %s for job %s: %s",
                                recipient_user_id,
                                job_id,
                                exc,
                            )
                            continue

                        _error_alert_cache.add(dedupe_key)
                        sent_count += 1
                        logger.info(
                            "Watcher: alert sent user_id=%s job_id=%s recipient=%s rule=%s dedupe_id=%s",
                            user.telegram_user_id,
                            job_id,
                            recipient_user_id,
                            matched_rule.key,
                            dedupe_id,
                        )

            return sent_count

    tasks = [asyncio.create_task(_scan_user(user)) for user in notification_users]
    results = await asyncio.gather(*tasks, return_exceptions=True)

    total_sent = 0
    for user, result in zip(notification_users, results):
        if isinstance(result, Exception):
            logger.error(
                "Watcher: error report scan failed for user %s: %s",
                user.telegram_user_id,
                result,
            )
            continue
        total_sent += int(result)

    return total_sent


async def _load_watcher_users() -> list[_WatcherUser]:
    conn = get_db_connection()
    if conn is None:
        return []

    user_rows = []
    try:
        async with conn.execute(
            """
            SELECT telegram_user_id,
                   deadline_login,
                   deadline_password,
                   notifications_enabled,
                   notification_scope,
                   preview_default_method,
                   preview_default_worker,
                   preview_auto_enabled,
                   preview_auto_scope
            FROM user_sessions
            """
        ) as cursor:
            user_rows = await cursor.fetchall()
    except Exception as exc:
        logger.error("Error fetching users for monitoring: %s", exc)
        return []

    users: list[_WatcherUser] = []
    for row in user_rows:
        (
            user_id,
            login,
            encrypted_password,
            notifications_enabled,
            scope_raw,
            preview_method_raw,
            preview_worker,
            preview_auto_enabled,
            preview_auto_scope_raw,
        ) = row

        if not user_id or not login or not encrypted_password:
            continue

        try:
            decrypted_password = _decrypt_password(encrypted_password)
        except Exception:
            decrypted_password = encrypted_password

        scope = _normalize_scope(scope_raw)
        auto_scope = _normalize_scope(preview_auto_scope_raw) if preview_auto_scope_raw else scope
        preview_method = (preview_method_raw or "").strip().lower()
        if preview_method not in VALID_PREVIEW_RENDER_METHODS:
            preview_method = None

        users.append(
            _WatcherUser(
                telegram_user_id=int(user_id),
                login=str(login),
                password=str(decrypted_password),
                notifications_enabled=bool(notifications_enabled),
                notification_scope=scope,
                auto_scope=auto_scope,
                preview_method=preview_method,
                preview_worker=preview_worker,
                auto_preview_enabled=bool(preview_auto_enabled),
            )
        )

    return users


def _collect_active_preview_targets(
    users: list[_WatcherUser],
) -> list[tuple[str, _WatcherUser]]:
    if not users or not preview_message_registry:
        return []

    users_by_id = {user.telegram_user_id: user for user in users}
    targets: list[tuple[str, _WatcherUser]] = []
    for preview_job_id, (chat_id, _message_id) in preview_message_registry.items():
        try:
            chat_id_int = int(chat_id)
        except (TypeError, ValueError):
            continue
        user = users_by_id.get(chat_id_int)
        if user is None:
            continue
        targets.append((preview_job_id, user))
    return targets


async def _process_active_preview_job(
    preview_job_id: str,
    user: _WatcherUser,
) -> None:
    from app.services.deadline import get_job_info_direct

    try:
        job = await get_job_info_direct(user.login, user.password, preview_job_id)
    except Exception as exc:
        logger.error(
            "Watcher: failed loading preview job %s for user %s: %s",
            preview_job_id,
            user.telegram_user_id,
            exc,
        )
        return

    if not job:
        return

    props = job.get("Props", {})
    if not _is_preview_job(props):
        return

    preview_owner_id = _extract_preview_owner_id(props, preview_job_id)
    target_user = preview_owner_id or user.telegram_user_id
    if target_user != user.telegram_user_id:
        return

    stat = job.get("Stat", 0)
    name = str(props.get("Name") or "").split("/")[-1]
    notified_key = (preview_job_id, target_user)

    if stat == 4:
        if notified_key in notified_jobs:
            return
        notified_user_id = await _notify_preview_job_failure(
            user.telegram_user_id,
            job,
            name,
            user.login,
            user.password,
        )
        resolved_user_id = notified_user_id or target_user
        notified_jobs.add((preview_job_id, resolved_user_id))
        return

    if stat != 3 or not _is_recently_completed(job, props):
        return

    if notified_key in notified_jobs:
        return

    notified_user_id = await _notify_preview_job_completion(
        user.telegram_user_id,
        job,
        name,
        user.login,
        user.password,
    )
    resolved_user_id = notified_user_id or target_user
    notified_jobs.add((preview_job_id, resolved_user_id))


async def _process_active_previews_parallel(
    targets: list[tuple[str, _WatcherUser]],
) -> None:
    if not targets:
        return

    max_parallel = min(8, max(1, len(targets)))
    semaphore = asyncio.Semaphore(max_parallel)

    async def _run(job_id: str, user: _WatcherUser) -> None:
        async with semaphore:
            await _process_active_preview_job(job_id, user)

    tasks = [asyncio.create_task(_run(job_id, user)) for job_id, user in targets]
    results = await asyncio.gather(*tasks, return_exceptions=True)
    for (job_id, user), result in zip(targets, results):
        if isinstance(result, Exception):
            logger.error(
                "Watcher: active preview processing failed for user %s job %s: %s",
                user.telegram_user_id,
                job_id,
                result,
            )


async def _register_auto_preview_history(telegram_user_id: int, job_id: str) -> bool:
    """Return True only for new (user, job) pairs, False when already processed."""
    conn = get_db_connection()
    if conn is None:
        return True

    try:
        async with conn.execute(
            """
            SELECT 1
            FROM auto_preview_history
            WHERE telegram_user_id = ? AND job_id = ?
            LIMIT 1
            """,
            (telegram_user_id, job_id),
        ) as cursor:
            if await cursor.fetchone():
                return False

        await conn.execute(
            """
            INSERT OR IGNORE INTO auto_preview_history (telegram_user_id, job_id, created_at)
            VALUES (?, ?, ?)
            """,
            (telegram_user_id, job_id, int(time.time())),
        )
        await conn.commit()
        return True
    except Exception as exc:
        logger.warning(
            "Watcher: failed to access auto_preview_history for user %s job %s: %s",
            telegram_user_id,
            job_id,
            exc,
        )
        # Fallback to in-memory dedupe only.
        return True


async def _maybe_cleanup_auto_preview_history() -> None:
    global _last_auto_preview_history_cleanup_monotonic

    now = time.monotonic()
    if (now - _last_auto_preview_history_cleanup_monotonic) < _AUTO_PREVIEW_HISTORY_CLEANUP_INTERVAL_SECONDS:
        return

    _last_auto_preview_history_cleanup_monotonic = now
    conn = get_db_connection()
    if conn is None:
        return

    cutoff = int(time.time()) - _AUTO_PREVIEW_HISTORY_RETENTION_SECONDS
    try:
        await conn.execute(
            "DELETE FROM auto_preview_history WHERE created_at < ?",
            (cutoff,),
        )
        await conn.commit()
    except Exception as exc:
        logger.warning("Watcher: failed to cleanup auto_preview_history: %s", exc)


async def _scan_auto_preview_candidates(users: list[_WatcherUser]) -> int:
    """Find newly completed non-preview jobs and enqueue auto-preview generation."""
    from app.services.deadline import get_jobs_by_credentials

    auto_users = [
        user
        for user in users
        if user.auto_preview_enabled and user.preview_method in {"server", "deadline"}
    ]
    if not auto_users:
        return 0

    await _maybe_cleanup_auto_preview_history()

    max_parallel = min(4, max(1, len(auto_users)))
    semaphore = asyncio.Semaphore(max_parallel)

    async def _scan_user(user: _WatcherUser) -> int:
        async with semaphore:
            try:
                jobs = await get_jobs_by_credentials(
                    user.login,
                    user.password,
                    use_cache=True,
                )
            except Exception as exc:
                logger.error(
                    "Watcher: failed to load jobs for auto-preview user %s: %s",
                    user.telegram_user_id,
                    exc,
                )
                return 0

            scheduled = 0
            for job in jobs:
                if not isinstance(job, dict):
                    continue

                job_id_raw = job.get("_id")
                job_id = str(job_id_raw).strip() if job_id_raw else ""
                if not job_id:
                    continue

                props = job.get("Props") or {}
                if not isinstance(props, dict):
                    props = {}

                if _is_preview_job(props):
                    continue

                if job.get("Stat", 0) != 3:
                    continue

                if not _is_recently_completed(job, props):
                    continue

                if not _job_matches_scope(user.auto_scope, user.login, props, job):
                    continue

                auto_key = (job_id, user.telegram_user_id)
                if auto_key in auto_preview_jobs:
                    continue

                is_new = await _register_auto_preview_history(user.telegram_user_id, job_id)
                if not is_new:
                    auto_preview_jobs.add(auto_key)
                    continue

                auto_preview_jobs.add(auto_key)
                job_name = str(props.get("Name") or "").split("/")[-1] or job_id
                asyncio.create_task(
                    _run_auto_preview_for_job(
                        user.telegram_user_id,
                        job_id,
                        job_name,
                        user.login,
                        user.password,
                        user.preview_method,
                        user.preview_worker,
                    )
                )
                scheduled += 1

            return scheduled

    tasks = [asyncio.create_task(_scan_user(user)) for user in auto_users]
    results = await asyncio.gather(*tasks, return_exceptions=True)

    total_scheduled = 0
    for user, result in zip(auto_users, results):
        if isinstance(result, Exception):
            logger.error(
                "Watcher: auto-preview scan failed for user %s: %s",
                user.telegram_user_id,
                result,
            )
            continue
        total_scheduled += int(result)

    return total_scheduled


async def job_progress_watcher(bot) -> None:
    """Monitor active preview jobs and auto-preview candidates."""
    del bot  # Runtime preview helpers use shared bot instance from bot_core.

    next_interval = settings.job_watcher_interval_normal
    next_auto_scan_at = 0.0
    next_error_scan_at = 0.0
    try:
        while True:
            loop_started = time.monotonic()
            users = await _load_watcher_users()

            active_targets = _collect_active_preview_targets(users)
            if active_targets:
                logger.debug(
                    "Watcher: processing %d active preview jobs",
                    len(active_targets),
                )
                await _process_active_previews_parallel(active_targets)

            auto_enabled_users = [
                user
                for user in users
                if user.auto_preview_enabled and user.preview_method in {"server", "deadline"}
            ]
            scheduled_count = 0
            auto_scan_interval = min(
                settings.job_watcher_interval_normal,
                _AUTO_PREVIEW_SCAN_INTERVAL_SECONDS,
            )
            if auto_enabled_users and loop_started >= next_auto_scan_at:
                scheduled_count = await _scan_auto_preview_candidates(auto_enabled_users)
                next_auto_scan_at = loop_started + auto_scan_interval
                if scheduled_count:
                    logger.info(
                        "Watcher: scheduled %d auto-preview job(s)",
                        scheduled_count,
                    )
            elif not auto_enabled_users:
                next_auto_scan_at = 0.0

            notification_users = [user for user in users if user.notifications_enabled]
            if notification_users and loop_started >= next_error_scan_at:
                alerts_sent = await _scan_error_reports_candidates(notification_users)
                next_error_scan_at = loop_started + _ERROR_REPORT_SCAN_INTERVAL_SECONDS
                if alerts_sent:
                    logger.info("Watcher: sent %d report alert(s)", alerts_sent)
            elif not notification_users:
                next_error_scan_at = 0.0

            if active_targets:
                next_interval = settings.job_watcher_interval_preview
            else:
                next_interval = settings.job_watcher_interval_normal
                if auto_enabled_users:
                    next_interval = min(next_interval, auto_scan_interval)
                if notification_users:
                    next_interval = min(next_interval, _ERROR_REPORT_SCAN_INTERVAL_SECONDS)

            await asyncio.sleep(next_interval)
    except asyncio.CancelledError:
        logger.info("Job progress watcher cancelled")
