"""Every account's previews are watched for failure, not only auto-preview ones.

22 Sep 2026: nodeb previewed SHC_0260_ID_v011 and SHD_0270_ID_v009 from the
chat while both renders were still queued. The previews failed about fifty
times each, alternating between NodeB and NodeC for two hours. The watcher saw
them - nodea's pass read the farm-wide job list - but rightly left them to
their owner, and their owner had no pass at all: the failure checks ran only
inside the auto-preview scan, and nodeb has auto previews off.
"""

import os
import sys
import unittest
from pathlib import Path
from unittest import mock

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

os.environ.setdefault("TELEGRAM_BOT_TOKEN", "123456:ABCDEFabcdef1234567890")
os.environ.setdefault("DEADLINE_API_URL", "https://example.local/api")
os.environ.setdefault(
    "ENCRYPTION_KEY", "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY="
)

from app.services import job_watcher
from app.services.preview import runtime


def failing_preview(owner: int, errors: int) -> dict:
    return {
        "_id": "prev1",
        "Stat": 1,
        "Errs": errors,
        "Props": {
            "Name": "SHC_0260_ID_v011 - /obj/ropnet1/SHD_0260_v002 - Preview",
            "Cmmt": "Preview job generated by TasksBot for src1",
            "ExDic": {"PreviewJob": "1", "PreviewTelegram": str(owner), "PreviewSource": "src1"},
        },
    }


def watcher_user(telegram_user_id: int, *, auto: bool) -> job_watcher._WatcherUser:
    return job_watcher._WatcherUser(
        telegram_user_id=telegram_user_id,
        login=f"login{telegram_user_id}",
        password="pw",
        notifications_enabled=False,
        notification_scope="own",
        auto_scope="own",
        preview_worker=None,
        auto_preview_enabled=auto,
    )


class EveryAccountIsWatchedTests(unittest.IsolatedAsyncioTestCase):
    async def _reconcile_all(self, users: list, jobs: list):
        with mock.patch(
            "app.services.deadline.get_jobs_by_credentials",
            new=mock.AsyncMock(return_value=jobs),
        ), mock.patch.object(
            job_watcher, "_strand_check", new=mock.AsyncMock(return_value=set())
        ), mock.patch.object(
            job_watcher, "_rescue_failing_preview", new=mock.AsyncMock()
        ) as rescue_mock:
            await job_watcher._reconcile_previews_of_all_users(users)
        return rescue_mock

    async def test_a_failing_preview_of_an_account_without_auto_previews_is_rescued(self) -> None:
        """nodeb's previews: auto previews off, errors piling up, nobody looking."""
        nodeb = watcher_user(100000002, auto=False)
        rescue = await self._reconcile_all(
            [nodeb], [failing_preview(100000002, job_watcher._PREVIEW_ERROR_LIMIT)]
        )
        rescue.assert_awaited_once()
        self.assertIs(rescue.await_args.args[0], nodeb)

    async def test_each_account_looks_after_its_own_previews(self) -> None:
        """nodea's pass saw nodeb's failing previews and rightly left them
        to their owner - who then had no pass of their own."""
        nodea = watcher_user(100000001, auto=True)
        nodeb = watcher_user(100000002, auto=False)
        jobs = [failing_preview(100000002, job_watcher._PREVIEW_ERROR_LIMIT)]
        with mock.patch(
            "app.services.deadline.get_jobs_by_credentials",
            new=mock.AsyncMock(return_value=jobs),
        ), mock.patch.object(
            job_watcher, "_strand_check", new=mock.AsyncMock(return_value=set())
        ), mock.patch(
            "app.services.deadline.delete_job", new=mock.AsyncMock(return_value=True)
        ) as delete_mock, mock.patch.object(
            job_watcher, "_rescue_stranded_preview", new=mock.AsyncMock()
        ) as replace_mock:
            job_watcher._recently_replaced_previews.clear()
            await job_watcher._reconcile_previews_of_all_users([nodea, nodeb])
        replace_mock.assert_awaited_once()
        self.assertIs(replace_mock.await_args.args[0], nodeb)
        delete_mock.assert_not_awaited()

    async def test_one_account_failing_does_not_stop_the_others(self) -> None:
        broken = watcher_user(1, auto=False)
        fine = watcher_user(2, auto=False)
        calls: list = []

        async def _reconcile(user, jobs):
            calls.append(user.telegram_user_id)
            if user is broken:
                raise RuntimeError("Deadline said no")

        with mock.patch(
            "app.services.deadline.get_jobs_by_credentials",
            new=mock.AsyncMock(return_value=[]),
        ), mock.patch.object(job_watcher, "_reconcile_previews", new=_reconcile):
            await job_watcher._reconcile_previews_of_all_users([broken, fine])
        self.assertEqual(calls, [1, 2])

    async def test_the_auto_preview_scan_no_longer_does_it_twice(self) -> None:
        with mock.patch(
            "app.services.deadline.get_jobs_by_credentials",
            new=mock.AsyncMock(return_value=[]),
        ), mock.patch.object(
            job_watcher, "_maybe_cleanup_auto_preview_history", new=mock.AsyncMock()
        ), mock.patch.object(
            job_watcher, "_reconcile_previews", new=mock.AsyncMock()
        ) as reconcile_mock:
            await job_watcher._scan_auto_preview_candidates([watcher_user(1, auto=True)])
        reconcile_mock.assert_not_awaited()


class ReplacementTests(unittest.IsolatedAsyncioTestCase):
    async def test_a_requested_preview_that_is_replaced_says_so(self) -> None:
        user = watcher_user(100000002, auto=False)
        props = failing_preview(100000002, 3)["Props"]
        runtime.preview_message_registry["prev1"] = (100000002, 55)
        try:
            with mock.patch(
                "app.services.deadline.delete_job", new=mock.AsyncMock(return_value=True)
            ), mock.patch(
                "app.services.preview.runtime._submit_auto_preview_deadline",
                new=mock.AsyncMock(return_value=True),
            ) as submit_mock, mock.patch.object(
                job_watcher.bot, "edit_message_text", new=mock.AsyncMock()
            ) as edit_mock:
                await job_watcher._rescue_stranded_preview(
                    user, "prev1", props, reason="it failed 3 times"
                )
        finally:
            runtime.preview_message_registry.pop("prev1", None)
        submit_mock.assert_awaited_once()
        self.assertEqual(submit_mock.await_args.args[1], "src1")
        edit_mock.assert_awaited_once()
        self.assertIn("queued again", edit_mock.await_args.args[0])
        self.assertEqual(edit_mock.await_args.kwargs["message_id"], 55)


if __name__ == "__main__":
    unittest.main()
