import os
import sys
import unittest
from pathlib import Path
from unittest import mock

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

os.environ.setdefault("TELEGRAM_BOT_TOKEN", "123456:ABCDEFabcdef1234567890")
os.environ.setdefault("DEADLINE_API_URL", "https://example.local/api")
os.environ.setdefault(
    "ENCRYPTION_KEY", "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY="
)

from app.services import job_watcher


def preview_props(*, presubmitted: bool, source_id: str = "src1", use_dict: bool = True) -> dict:
    props = {
        "Name": "Shot - Preview",
        "Cmmt": "Preview job generated by TasksBot for src1",
    }
    extra = {"PreviewJob": "1", "PreviewSource": source_id}
    if presubmitted:
        extra["PreviewPresubmit"] = "1"
    if use_dict:
        props["ExDic"] = extra
    else:
        for index, (key, value) in enumerate(extra.items()):
            props[f"ExtraInfoKeyValue{index}"] = f"{key}={value}"
    return props


class PresubmitDetectionTests(unittest.TestCase):
    def test_detects_marker_in_dict(self) -> None:
        self.assertTrue(job_watcher._is_presubmitted_preview(preview_props(presubmitted=True)))

    def test_detects_marker_in_key_values(self) -> None:
        self.assertTrue(
            job_watcher._is_presubmitted_preview(
                preview_props(presubmitted=True, use_dict=False)
            )
        )

    def test_manual_preview_is_not_presubmitted(self) -> None:
        self.assertFalse(job_watcher._is_presubmitted_preview(preview_props(presubmitted=False)))
        self.assertFalse(
            job_watcher._is_presubmitted_preview(
                preview_props(presubmitted=False, use_dict=False)
            )
        )
        self.assertFalse(job_watcher._is_presubmitted_preview({}))


class PresubmitReadyTests(unittest.TestCase):
    """Previews are queued as soon as the render is genuinely running."""

    def test_running_render_is_ready(self) -> None:
        job = {"RenderingChunks": 2, "QueuedChunks": 34, "CompletedChunks": 0}
        self.assertTrue(job_watcher._presubmit_ready(job, {"Tasks": 40}))

    def test_render_with_finished_frames_is_ready(self) -> None:
        job = {"RenderingChunks": 0, "QueuedChunks": 10, "CompletedChunks": 5}
        self.assertTrue(job_watcher._presubmit_ready(job, {"Tasks": 40}))

    def test_idle_or_failing_render_is_not_ready(self) -> None:
        self.assertFalse(
            job_watcher._presubmit_ready({"QueuedChunks": 40}, {"Tasks": 40})
        )
        self.assertFalse(
            job_watcher._presubmit_ready(
                {"RenderingChunks": 1, "FailedChunks": 1}, {"Tasks": 40}
            )
        )

    def test_single_task_render_is_ready(self) -> None:
        # Stills used to be excluded; with a Pending dependency they are fine.
        job = {"RenderingChunks": 1}
        self.assertTrue(job_watcher._presubmit_ready(job, {"Tasks": 1}))


class ReconcileScopeTests(unittest.IsolatedAsyncioTestCase):
    """Only pre-submitted previews of dead renders get cleaned up."""

    def _jobs(self, presubmitted: bool, source_stat: int, preview_stat: int = 6) -> list:
        source = {
            "_id": "src1",
            "Stat": source_stat,
            "QueuedChunks": 34,
            "RenderingChunks": 2,
            "Props": {"Name": "Shot"},
        }
        preview = {
            "_id": "prev1",
            "Stat": preview_stat,  # 6 = pending on the dependency
            "Props": preview_props(presubmitted=presubmitted),
        }
        return [source, preview]

    async def _reconcile(self, jobs: list):
        user = mock.Mock(telegram_user_id=42, login="tester", password="pw")
        with mock.patch(
            "app.services.preview.runtime._extract_preview_context",
            return_value=("", "", "", 42, {}, "src1"),
        ), mock.patch(
            "app.services.preview.runtime.pop_preview_message", return_value=None
        ), mock.patch(
            "app.services.deadline.delete_job", new=mock.AsyncMock(return_value=True)
        ) as delete_mock, mock.patch.object(
            job_watcher, "_unregister_auto_preview_history", new=mock.AsyncMock()
        ):
            await job_watcher._reconcile_presubmitted_previews(user, jobs)
        return delete_mock

    async def test_pending_preview_of_running_render_untouched(self) -> None:
        delete_mock = await self._reconcile(self._jobs(presubmitted=True, source_stat=1))
        delete_mock.assert_not_awaited()

    async def test_pending_preview_of_failed_render_removed(self) -> None:
        delete_mock = await self._reconcile(self._jobs(presubmitted=True, source_stat=4))
        delete_mock.assert_awaited_once()

    async def test_manual_preview_never_removed(self) -> None:
        delete_mock = await self._reconcile(self._jobs(presubmitted=False, source_stat=4))
        delete_mock.assert_not_awaited()


if __name__ == "__main__":
    unittest.main()
