import os
import sys
import unittest
from pathlib import Path
from unittest import mock

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

os.environ.setdefault("TELEGRAM_BOT_TOKEN", "123456:ABCDEFabcdef1234567890")
os.environ.setdefault("DEADLINE_API_URL", "https://example.local/api")
os.environ.setdefault(
    "ENCRYPTION_KEY", "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY="
)

from app.services import job_watcher


def preview_props(*, presubmitted: bool, source_id: str = "src1", use_dict: bool = True) -> dict:
    props = {
        "Name": "Shot - Preview",
        "Cmmt": "Preview job generated by TasksBot for src1",
    }
    extra = {"PreviewJob": "1", "PreviewSource": source_id}
    if presubmitted:
        extra["PreviewPresubmit"] = "1"
    if use_dict:
        props["ExDic"] = extra
    else:
        for index, (key, value) in enumerate(extra.items()):
            props[f"ExtraInfoKeyValue{index}"] = f"{key}={value}"
    return props


class PresubmitDetectionTests(unittest.TestCase):
    def test_detects_marker_in_dict(self) -> None:
        self.assertTrue(job_watcher._is_presubmitted_preview(preview_props(presubmitted=True)))

    def test_detects_marker_in_key_values(self) -> None:
        self.assertTrue(
            job_watcher._is_presubmitted_preview(
                preview_props(presubmitted=True, use_dict=False)
            )
        )

    def test_manual_preview_is_not_presubmitted(self) -> None:
        self.assertFalse(job_watcher._is_presubmitted_preview(preview_props(presubmitted=False)))
        self.assertFalse(
            job_watcher._is_presubmitted_preview(
                preview_props(presubmitted=False, use_dict=False)
            )
        )
        self.assertFalse(job_watcher._is_presubmitted_preview({}))


class ReconcileScopeTests(unittest.IsolatedAsyncioTestCase):
    """A rendering job with queued tasks must not suspend a manual preview."""

    def _jobs(self, presubmitted: bool) -> list:
        source = {
            "_id": "src1",
            "Stat": 1,  # active render
            "QueuedChunks": 34,
            "RenderingChunks": 2,
            "Props": {"Name": "Shot"},
        }
        preview = {
            "_id": "prev1",
            "Stat": 1,  # queued preview
            "Props": preview_props(presubmitted=presubmitted),
        }
        return [source, preview]

    async def _reconcile(self, presubmitted: bool):
        user = mock.Mock(telegram_user_id=42, login="tester", password="pw")
        with mock.patch(
            "app.services.preview.runtime._extract_preview_context",
            return_value=("", "", "", 42, {}, "src1"),
        ), mock.patch(
            "app.services.deadline.suspend_job", new=mock.AsyncMock(return_value=True)
        ) as suspend_mock, mock.patch(
            "app.services.deadline.resume_job", new=mock.AsyncMock(return_value=True)
        ), mock.patch(
            "app.services.deadline.delete_job", new=mock.AsyncMock(return_value=True)
        ) as delete_mock:
            await job_watcher._reconcile_presubmitted_previews(user, self._jobs(presubmitted))
        return suspend_mock, delete_mock

    async def test_manual_preview_untouched(self) -> None:
        suspend_mock, delete_mock = await self._reconcile(presubmitted=False)
        suspend_mock.assert_not_awaited()
        delete_mock.assert_not_awaited()

    async def test_presubmitted_preview_suspended(self) -> None:
        suspend_mock, _ = await self._reconcile(presubmitted=True)
        suspend_mock.assert_awaited_once()


if __name__ == "__main__":
    unittest.main()
